### ISSUE TITLE
keep releases option

### ISSUE THREAD

**Issue by idoo** [dasuchin/grunt-ssh-deploy#10]
hey guys, what about keep release options?)

**Comment by gintsgints** [comment]
What is that? :)

**Comment by idoo** [comment]
@gintsgints remove old release, but leave N lastet

**Comment by hurricane766** [comment]
+1, the releases can add up overtime. There's no link to the old releases so it would be like this:
``rm -rf `ls -t | awk 'NR>#'` `` , where # is the number of directories you'd like to keep. I haven't tried this but I took it from [here](http://stackoverflow.com/questions/25785/delete-all-but-the-most-recent-x-files-in-bash)

**Comment by gintsgints** [comment]
It could be done probably with doAfter :)

**Comment by winknudge-tomm** [comment]
@hurricane766 Someone has proposed a similar solution [here](http://stackoverflow.com/questions/4126869/bash-command-to-delete-all-but-last-5-directories) 

rm `ls -t | tail -n +6` 

where 6 is the number of directories to keep, would probably have to add the -rf flags in too though. 

Going to give it a go if I get chance today and report back.

**Comment by hurricane766** [comment]
This is now an option in the current version. Close?

**Comment by idoo** [comment]
@hurricane766 yep
