### ISSUE TITLE
Task won't run

### ISSUE THREAD

**Issue by dahliacreative** [dasuchin/grunt-ssh-deploy#12]
When I try to run my task, I keep getting:
```
Running "ssh_deploy:staging" (ssh_deploy) task
Warning: Cannot read property 'staging' of undefined Use --force to continue.
```
I am using load-grunt-config and my config file looks like this:

```
module.exports = {
  environments: {
    staging: {
      options: {
        host: '<%= secret.staging.host %>',
        username: '<%= secret.staging.username %>',
        password: '<%= secret.staging.password %>',
        port: '<%= secret.staging.port %>',
        deploy_path: '<%= secret.staging.deployPath %>',
        local_path: '<%= secret.staging.localPath %>',
        current_symlink: 'current',
        debug: true
      }
    }
  }
}
```

Any Ideas, I'm completely stumped.
Cheers.

**Comment by vlrprbttst** [comment]
what does a "secret.json" file look like? i'm talking about syntax

**Comment by hurricane766** [comment]
A JSON object. So at minimum:
      {}
      
      But probably:
      {
          "staging": {
              "host": "192.168.1.2",
              "username": "user",
              etc...
          },
          "production":{
              "host": 192.168.1.4,
              "username": "user",
              etc...
          }
      }
      
      So secret.staging.host would resolve to "192.168.1.2"
      
      On 2/11/2015 8:08 AM, Valerio wrote:
    
    
      what does a "secret.json" file look like? i'm talking about
        syntax
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by colmose** [comment]
If you're still having this problem, change the name of your task config script to environments.js and remove the environments object from within. 

So environments.js will have:

module.exports = {
     staging:{
          options: {
              host: '<%= secret.staging.host %>',
              username: '<%= secret.staging.username %>',
              password: '<%= secret.staging.password %>',
              port: '<%= secret.staging.port %>',
             deploy_path: '<%= secret.staging.deployPath %>',
             local_path: '<%= secret.staging.localPath %>',
             current_symlink: 'current',
             debug: true
          }
     }
}

This worked for me anyway!
