### ISSUE TITLE
Bump the version number and Rebuild the package

### ISSUE THREAD

**Issue by hurricane766** [dasuchin/grunt-ssh-deploy#13]
`npm install grunt-ssh-deploy`

installs a version without some of the newer bug fixes.

This has caused some headaches:
https://github.com/dasuchin/grunt-ssh-deploy/issues/11

**Comment by gintsgints** [comment]
+1 for this. But who is responsive for package update?

**Comment by dasuchin** [comment]
Updated the package on npm.
