### ISSUE TITLE
Ignore files during deployment

### ISSUE THREAD

**Issue by SiamKreative** [dasuchin/grunt-ssh-deploy#27]
Hello there,

In most projects I use [grunt-dploy](https://github.com/LeanMeanFightingMachine/grunt-dploy) to deploy my local projects. It has an option to exclude stuff. Normally, I exclude the following files and folders: like `*.less`, `*.coffee`, `*/node_modules`.

What's the workflow with **grunt-ssh-deploy**? Also, I don't understand how you deal with the different releases folders that are created. I'd be grateful if you can provide further explanation :)

Thanks

**Comment by lochstar** [comment]
I deploy my dist directory, which contains a compressed production copy of my application that already has the files I don't need excluded.

**Comment by hurricane766** [comment]
Same here, @lochstar

**Comment by SiamKreative** [comment]
Thanks guys @lochstar @hurricane766!

I know this is a bit off topic, but is it a good practice to have a dist folder created with Grunt? Is there a great tutorial that explains how to structure the Gruntfile properly with tasks like `contrib-concat`, `uglify`, `contrib-less`, `ssh-deploy`?

**Comment by lochstar** [comment]
I have a task named grunt build that prepares my project for distribution. I have a series of tasks that are run one after another.
e.g.

    grunt.registerTask('build', 'Builds web app to dist directory', function() {
        grunt.log.writeln('Building webapp...');
        grunt.task.run([
            'clean:dist',
            'exec:translations',
            'string-replace:index',
            'requirejs',
            'clean:requirejs',
            'cachebreaker',
            'processhtml:dist',
            'copy:help',
            'less:dist',
            'uglify:dist'
        ]);
    });
