### ISSUE TITLE
Error: Timed out while waiting for handshake

### ISSUE THREAD

**Issue by pixelstorm** [dasuchin/grunt-ssh-deploy#31]
Connecting with ssh manually works for me,
when i try to deploy using ssh_deploy i get

Error: Timed out while waiting for handshake

My config:

    secret: grunt.file.readJSON('secret.json'),

    environments: {
        theme: {
            options: {
                host: '<%= secret.theme.host %>',
                username: '<%= secret.theme.username %>',
                password: '<%= secret.theme.password %>',
                port: '<%= secret.theme.port %>',
                deploy_path: '/public_html/newfolder',
		readyTimeout: 99999,
                local_path: '../wp-content/themes/mytheme/',
                current_symlink: 'current',
                debug: console.log 
            }
        },

The command:
grunt ssh_deploy:theme

The Output:
Running "ssh_deploy:theme" (ssh_deploy) task

Connecting :: myserver.com
DEBUG: Parser: STATE_INIT

**Comment by kenho1703** [comment]
hot to fix this issue?

**Comment by OleksandrPoltavets** [comment]
+1 I have the same issue

**Comment by mmhan** [comment]
+1 I have the same issue as well. It might be good to have an option of specifying your own timeout.
