### ISSUE TITLE
Not able to connect to windows server machine for deploy

### ISSUE THREAD

**Issue by ag13** [dasuchin/grunt-ssh-deploy#38]
I am trying to deploy an artifact to a remote Windows machine. It gives me a connection error.

Error: connect ECONNREFUSED
Fatal error: connect ECONNREFUSED
Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1000:19)

**Comment by dasuchin** [comment]
That looks to me like it is an issue with the machine itself and not the plugin. Is there any other details you're able to get?
